# Generated by Django 3.0.4 on 2020-04-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Qual seu nome?')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Qual o número do seu Whatsapp?')),
                ('titulo', models.CharField(max_length=50, verbose_name='Qual o seu Pedido?')),
                ('categoria', models.CharField(choices=[('Cesta Básica', 'Cesta Básica'), ('Remédios', 'Remédios'), ("EPI's", "EPI's")], default='Cesta Básica', max_length=50, verbose_name='Escolha uma categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descreva o que você está precisando')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
