# Generated by Django 3.0.4 on 2020-04-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantee',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Qual o seu pedido de ajuda?'),
        ),
    ]
