# Generated by Django 3.0.5 on 2020-04-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('donatario', '0004_grantee_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantee',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='municipios.UF'),
        ),
    ]
