# Generated by Django 3.0.4 on 2020-04-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donatario', '0004_auto_20200405_1835'),
        ('doador', '0002_auto_20200405_2014'),
        ('doacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='sexo',
        ),
        migrations.AddField(
            model_name='donation',
            name='doador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doador.Donor', verbose_name='Doador'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donatario.Grantee', verbose_name='Donatario'),
        ),
    ]
