# Generated by Django 3.0.4 on 2020-04-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0002_auto_20200405_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='avisado',
            field=models.BooleanField(default=False),
        ),
    ]
