# Generated by Django 3.0.4 on 2020-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.AddField(
            model_name='donor',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Qual seu nome?'),
        ),
        migrations.AddField(
            model_name='donor',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True, verbose_name='Qual o número do seu Whatsapp?'),
        ),
    ]
