# Generated by Django 3.0.4 on 2020-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0002_auto_20200405_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True, verbose_name='Whastapp'),
        ),
    ]
